/-
# Ideal theorem targets for the dynamic SOC/Hopf--Cole layer
-/

import ChenGeorgiouPavon2021.SocOt.Dynamic
import ChenGeorgiouPavon2021.EnergyIdentityTargets

set_option autoImplicit false

open MeasureTheory ProbabilityTheory
open scoped ENNReal BigOperators

namespace ChenGeorgiouPavon2021

variable {X : Type*} [MeasurableSpace X] [NormedAddCommGroup X] [NormedSpace ℝ X]

variable (d : SBData X)

omit [NormedSpace ℝ X] in
/-- Existence target for a feasible control steering the two prescribed marginals.

For an arbitrary abstract `SBData`, feasibility is not automatic: the path-law family might not
realize any bridge between the requested endpoints.  The theorem is therefore stated from two
independent, non-circular construction inputs: an admissible bridge path law with the desired
endpoints, and a realization theorem saying such an admissible path law is generated by some
control. -/
theorem feasible_control_exists_of_cgp_hypotheses
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (hadm : ∃ P : ProbabilityMeasure (Path X),
      initialMarginal P = (ρ₀ : Measure X) ∧
      terminalMarginal P = (ρ₁ : Measure X) ∧
      (P : Measure (Path X)) ≪ (d.R : Measure (Path X)))
    (hrealize : ∀ P : ProbabilityMeasure (Path X),
      initialMarginal P = (ρ₀ : Measure X) →
      terminalMarginal P = (ρ₁ : Measure X) →
      (P : Measure (Path X)) ≪ (d.R : Measure (Path X)) →
      ∃ u : Control X, d.pathLaw u ρ₀ = P) :
    ∃ u : Control X, Feasible d u ρ₀ ρ₁ := by
  obtain ⟨P, hP0, hP1, hPac⟩ := hadm
  obtain ⟨u, hPu⟩ := hrealize P hP0 hP1 hPac
  refine ⟨u, ?_, ?_⟩
  · rw [hPu]
    exact hP0
  · rw [hPu]
    exact hP1

/-- Energy-identity family target supplying the hypothesis of `schrodingerBridge_KL_eq_SOC`. -/
theorem energyIdentity_family_of_finiteEnergyDiffusion
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (hfed : ∀ u : Control X, Feasible d u ρ₀ ρ₁ → FiniteEnergyDiffusion d u ρ₀) :
    ∀ u : Control X, Feasible d u ρ₀ ρ₁ →
      klReal (d.pathLaw u ρ₀ : Measure (Path X)) (d.R : Measure (Path X))
        = klReal (initialMarginal (d.pathLaw u ρ₀)) (initialMarginal d.R)
          + energy u (d.pathLaw u ρ₀) := by
  intro u hu
  exact klReal_pathLaw_eq_initialKL_add_energy_of_finiteEnergyDiffusion d u ρ₀ ρ₁ hu (hfed u hu)

/-- Hopf--Cole verification theorem target: the logarithmic-transform feedback control is optimal.

This is where the Schrödinger PDE system, verification theorem, SDE well-posedness, and endpoint
constraints should enter.  The existing characterization theorem then turns this optimality plus
uniqueness into the pointwise formula `u* = ∇ log φ`. -/
theorem hopfCole_control_isOptimalSOC_of_schrodingerSystem
    (grad : (X → ℝ) → X → X) (lap : (X → ℝ) → X → ℝ)
    (φ φhat : ℝ → X → ℝ) (dens0 dens1 : X → ℝ)
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (_hsys : SchrodingerSystem (d.sigma ^ 2) lap φ φhat dens0 dens1)
    (_hφpos : ∀ t x, 0 < φ t x) :
    IsOptimalSOC d (fun t x => grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁ := by
  sorry

/-- Diffusion-scaled Hopf--Cole verification theorem for CGP Theorem 5.2.

This is not an independent analytic target: it is the ordinary Hopf--Cole verification theorem
applied to the first-order operator `f ↦ σ² • grad f`.  The real SDE/PDE work remains isolated in
`hopfCole_control_isOptimalSOC_of_schrodingerSystem`. -/
theorem sigmaHopfCole_control_isOptimalSOC_of_schrodingerSystem
    (grad : (X → ℝ) → X → X) (lap : (X → ℝ) → X → ℝ)
    (φ φhat : ℝ → X → ℝ) (dens0 dens1 : X → ℝ)
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (hsys : SchrodingerSystem (d.sigma ^ 2) lap φ φhat dens0 dens1)
    (hφpos : ∀ t x, 0 < φ t x) :
    IsOptimalSOC d (fun t x => (d.sigma ^ 2) • grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁ := by
  simpa using
    hopfCole_control_isOptimalSOC_of_schrodingerSystem d
      (fun f x => (d.sigma ^ 2) • grad f x) lap φ φhat dens0 dens1 ρ₀ ρ₁ hsys hφpos

/-- Uniqueness target for the stochastic optimal-control optimizer. -/
theorem soc_optimizer_unique_of_strictConvexEnergy
    (ρ₀ ρ₁ : ProbabilityMeasure X) :
    ∀ u u' : Control X,
      IsOptimalSOC d u ρ₀ ρ₁ → IsOptimalSOC d u' ρ₀ ρ₁ → u = u' := by
  sorry

/-- HJB verification target: a value-gradient feedback is optimal. -/
theorem valueGradient_control_isOptimalSOC_of_HamiltonJacobi
    (grad : (X → ℝ) → X → X) (lam : ℝ → X → ℝ)
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (_hHJ : HamiltonJacobi grad lam) :
    IsOptimalSOC d (fun t x => grad (lam t) x) ρ₀ ρ₁ := by
  sorry

end ChenGeorgiouPavon2021
