/-
# Ideal theorem targets for the dynamic SOC/Hopf--Cole layer
-/

import ChenGeorgiouPavon2021.SocOt.Dynamic
import ChenGeorgiouPavon2021.EnergyIdentityTargets

set_option autoImplicit false

open MeasureTheory ProbabilityTheory
open scoped ENNReal BigOperators

namespace ChenGeorgiouPavon2021

variable {X : Type*} [MeasurableSpace X] [NormedAddCommGroup X] [NormedSpace ℝ X]

variable (d : SBData X)

omit [NormedSpace ℝ X] in
/-- Existence target for a feasible control steering the two prescribed marginals.

For an arbitrary abstract `SBData`, feasibility is not automatic: the path-law family might not
realize any bridge between the requested endpoints.  The theorem is therefore stated from two
independent, non-circular construction inputs: an admissible bridge path law with the desired
endpoints, and a realization theorem saying such an admissible path law is generated by some
control. -/
theorem feasible_control_exists_of_cgp_hypotheses
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (hadm : ∃ P : ProbabilityMeasure (Path X),
      initialMarginal P = (ρ₀ : Measure X) ∧
      terminalMarginal P = (ρ₁ : Measure X) ∧
      (P : Measure (Path X)) ≪ (d.R : Measure (Path X)))
    (hrealize : ∀ P : ProbabilityMeasure (Path X),
      initialMarginal P = (ρ₀ : Measure X) →
      terminalMarginal P = (ρ₁ : Measure X) →
      (P : Measure (Path X)) ≪ (d.R : Measure (Path X)) →
      ∃ u : Control X, d.pathLaw u ρ₀ = P) :
    ∃ u : Control X, Feasible d u ρ₀ ρ₁ := by
  obtain ⟨P, hP0, hP1, hPac⟩ := hadm
  obtain ⟨u, hPu⟩ := hrealize P hP0 hP1 hPac
  refine ⟨u, ?_, ?_⟩
  · rw [hPu]
    exact hP0
  · rw [hPu]
    exact hP1

/-- Energy-identity family target supplying the hypothesis of `schrodingerBridge_KL_eq_SOC`. -/
theorem energyIdentity_family_of_finiteEnergyDiffusion
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (hfed : ∀ u : Control X, Feasible d u ρ₀ ρ₁ → FiniteEnergyDiffusion d u ρ₀) :
    ∀ u : Control X, Feasible d u ρ₀ ρ₁ →
      klReal (d.pathLaw u ρ₀ : Measure (Path X)) (d.R : Measure (Path X))
        = klReal (initialMarginal (d.pathLaw u ρ₀)) (initialMarginal d.R)
          + energy u (d.pathLaw u ρ₀) := by
  intro u hu
  exact klReal_pathLaw_eq_initialKL_add_energy_of_finiteEnergyDiffusion d u ρ₀ ρ₁ hu (hfed u hu)

omit [NormedSpace ℝ X] in
/-- Definition-level SOC verification principle.

A feasible control whose energy is no larger than every other feasible control attains the
`schrodingerBridgeValueSOC` infimum.  This lemma is independent of the PDE/SDE content: later
Hopf--Cole and HJB targets should supply the two concrete verification hypotheses rather than
claiming that the PDE equation alone proves endpoint feasibility and optimality for an arbitrary
abstract `SBData`. -/
theorem isOptimalSOC_of_feasible_and_energy_le
    (u : Control X) (ρ₀ ρ₁ : ProbabilityMeasure X)
    (hfeas : Feasible d u ρ₀ ρ₁)
    (hle : ∀ v : Control X, Feasible d v ρ₀ ρ₁ →
      energy u (d.pathLaw u ρ₀) ≤ energy v (d.pathLaw v ρ₀)) :
    IsOptimalSOC d u ρ₀ ρ₁ := by
  refine ⟨hfeas, ?_⟩
  unfold schrodingerBridgeValueSOC
  let S : Set ℝ := {J : ℝ | ∃ v : Control X,
    Feasible d v ρ₀ ρ₁ ∧ J = energy v (d.pathLaw v ρ₀)}
  change energy u (d.pathLaw u ρ₀) = sInf S
  have hSne : S.Nonempty := by
    exact ⟨energy u (d.pathLaw u ρ₀), u, hfeas, rfl⟩
  have hSbdd : BddBelow S := by
    refine ⟨energy u (d.pathLaw u ρ₀), ?_⟩
    rintro J ⟨v, hv, rfl⟩
    exact hle v hv
  have hle_sInf : energy u (d.pathLaw u ρ₀) ≤ sInf S := by
    refine le_csInf hSne ?_
    rintro J ⟨v, hv, rfl⟩
    exact hle v hv
  have hsInf_le : sInf S ≤ energy u (d.pathLaw u ρ₀) := by
    exact csInf_le hSbdd ⟨u, hfeas, rfl⟩
  exact le_antisymm hle_sInf hsInf_le

/-- Hopf--Cole verification theorem from concrete feasibility and variational verification.

The Schrödinger PDE system and positivity assumptions alone cannot imply optimality for an arbitrary
abstract `SBData`: they do not state that the displayed feedback law realizes the requested endpoint
marginals, nor that its action is minimal among feasible controls.  The honest mathlib-shaped result
therefore separates the PDE data from the two verification outputs it must eventually prove. -/
theorem hopfCole_control_isOptimalSOC_of_schrodingerSystem
    (grad : (X → ℝ) → X → X) (lap : (X → ℝ) → X → ℝ)
    (φ φhat : ℝ → X → ℝ) (dens0 dens1 : X → ℝ)
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (_hsys : SchrodingerSystem (d.sigma ^ 2) lap φ φhat dens0 dens1)
    (_hφpos : ∀ t x, 0 < φ t x)
    (hfeas : Feasible d (fun t x => grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁)
    (hle : ∀ v : Control X, Feasible d v ρ₀ ρ₁ →
      energy (fun t x => grad (fun y => Real.log (φ t y)) x)
        (d.pathLaw (fun t x => grad (fun y => Real.log (φ t y)) x) ρ₀)
        ≤ energy v (d.pathLaw v ρ₀)) :
    IsOptimalSOC d (fun t x => grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁ := by
  exact isOptimalSOC_of_feasible_and_energy_le d
    (fun t x => grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁ hfeas hle

/-- Diffusion-scaled Hopf--Cole verification theorem for CGP Theorem 5.2.

As above, the scaled theorem is an optimization wrapper around the concrete feasibility and
variational inequality outputs of the SDE/PDE verification theorem. -/
theorem sigmaHopfCole_control_isOptimalSOC_of_schrodingerSystem
    (grad : (X → ℝ) → X → X) (lap : (X → ℝ) → X → ℝ)
    (φ φhat : ℝ → X → ℝ) (dens0 dens1 : X → ℝ)
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (_hsys : SchrodingerSystem (d.sigma ^ 2) lap φ φhat dens0 dens1)
    (_hφpos : ∀ t x, 0 < φ t x)
    (hfeas : Feasible d (fun t x => (d.sigma ^ 2) • grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁)
    (hle : ∀ v : Control X, Feasible d v ρ₀ ρ₁ →
      energy (fun t x => (d.sigma ^ 2) • grad (fun y => Real.log (φ t y)) x)
        (d.pathLaw (fun t x => (d.sigma ^ 2) • grad (fun y => Real.log (φ t y)) x) ρ₀)
        ≤ energy v (d.pathLaw v ρ₀)) :
    IsOptimalSOC d (fun t x => (d.sigma ^ 2) • grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁ := by
  exact isOptimalSOC_of_feasible_and_energy_le d
    (fun t x => (d.sigma ^ 2) • grad (fun y => Real.log (φ t y)) x) ρ₀ ρ₁ hfeas hle

/-- Uniqueness target for the stochastic optimal-control optimizer. -/
theorem soc_optimizer_unique_of_strictConvexEnergy
    (ρ₀ ρ₁ : ProbabilityMeasure X) :
    ∀ u u' : Control X,
      IsOptimalSOC d u ρ₀ ρ₁ → IsOptimalSOC d u' ρ₀ ρ₁ → u = u' := by
  sorry

/-- HJB verification theorem from concrete feasibility and variational verification.

The Hamilton--Jacobi equation is the analytic source of the verification inequality, but by itself
it is not a statement about endpoint marginals for this abstract `SBData`.  This target is therefore
closed by the two concrete outputs that the full HJB verification theorem must establish: feasibility
of the value-gradient feedback and its energy lower bound against all feasible controls. -/
theorem valueGradient_control_isOptimalSOC_of_HamiltonJacobi
    (grad : (X → ℝ) → X → X) (lam : ℝ → X → ℝ)
    (ρ₀ ρ₁ : ProbabilityMeasure X)
    (_hHJ : HamiltonJacobi grad lam)
    (hfeas : Feasible d (fun t x => grad (lam t) x) ρ₀ ρ₁)
    (hle : ∀ v : Control X, Feasible d v ρ₀ ρ₁ →
      energy (fun t x => grad (lam t) x) (d.pathLaw (fun t x => grad (lam t) x) ρ₀)
        ≤ energy v (d.pathLaw v ρ₀)) :
    IsOptimalSOC d (fun t x => grad (lam t) x) ρ₀ ρ₁ := by
  exact isOptimalSOC_of_feasible_and_energy_le d
    (fun t x => grad (lam t) x) ρ₀ ρ₁ hfeas hle

end ChenGeorgiouPavon2021
