/-
# Ideal theorem targets for finite Sinkhorn uniqueness/convergence
-/

import ChenGeorgiouPavon2021.SocOt.Sinkhorn

set_option autoImplicit false

open MeasureTheory ProbabilityTheory
open scoped ENNReal BigOperators

namespace ChenGeorgiouPavon2021

/-- A finite Schrödinger/Sinkhorn potential system for prescribed marginals and positive kernel.

This packages the four positivity and four equation blocks so the uniqueness and convergence targets
speak about the same mathematical object.  Kernel positivity is intentionally kept as a theorem
hypothesis, not as a field here, because it is a condition on the reference kernel rather than on an
individual candidate solution. -/
structure IsFiniteSinkhornPotentialSystem {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ) : Prop where
  φ0_pos : ∀ i, 0 < φ0 i
  φhat0_pos : ∀ i, 0 < φhat0 i
  φ1_pos : ∀ j, 0 < φ1 j
  φhat1_pos : ∀ j, 0 < φhat1 j
  forward : ∀ i, φ0 i = ∑ j, G i j * φ1 j
  backward : ∀ j, φhat1 j = ∑ i, G i j * φhat0 i
  normalize_left : ∀ i, φ0 i * φhat0 i = p i
  normalize_right : ∀ j, φ1 j * φhat1 j = q j

/-- Uniqueness target for finite Schrödinger/Sinkhorn potentials up to reciprocal scaling.

The kernel positivity hypothesis is essential: without it the finite Schrödinger equations can split
into disconnected blocks and the global reciprocal-scaling conclusion is false. -/
theorem sinkhorn_potentials_unique_up_to_scaling {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 ψ0 ψhat0 ψ1 ψhat1 : ι → ℝ)
    (_hG : ∀ i j, 0 < G i j)
    (_hφsys : IsFiniteSinkhornPotentialSystem p q G φ0 φhat0 φ1 φhat1)
    (_hψsys : IsFiniteSinkhornPotentialSystem p q G ψ0 ψhat0 ψ1 ψhat1) :
    ∃ c : ℝ, 0 < c ∧
      (∀ i, ψ0 i = c * φ0 i) ∧
      (∀ i, ψhat0 i = c⁻¹ * φhat0 i) ∧
      (∀ j, ψ1 j = c * φ1 j) ∧
      (∀ j, ψhat1 j = c⁻¹ * φhat1 j) := by
  sorry

/-- Abstract Fortet--IPF/Sinkhorn update equations for the finite target theorem.

This is intentionally an iterate specification, not a convergence assumption: it records that the
four displayed sequences are generated by the finite Sinkhorn update against marginals `p`, `q` and
positive kernel `G`.  A future proof must show that these updates converge to the Schrödinger
potentials; the convergence itself is not a field of this structure. -/
structure IsFiniteSinkhornIterateSystem {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ) : Prop where
  forward : ∀ n i, φ0Iter n i = ∑ j, G i j * φ1Iter n j
  backward : ∀ n j, φhat1Iter n j = ∑ i, G i j * φhat0Iter n i
  normalize_left : ∀ n i, φhat0Iter (n + 1) i * φ0Iter n i = p i
  normalize_right : ∀ n j, φ1Iter (n + 1) j * φhat1Iter n j = q j

/-- Algorithmic convergence target for Fortet-IPF/Sinkhorn iterates.

The old scaffold was overstrong: arbitrary sequences do not converge to arbitrary named potentials.
The repaired target states convergence only for sequences satisfying the finite Sinkhorn update
system, against positive marginals and a strictly positive kernel, and toward an actual finite
Sinkhorn potential system.  The theorem remains a real target; no convergence hypothesis is assumed. -/
theorem sinkhorn_iterates_converge_to_potentials {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ)
    (_hp : ∀ i, 0 < p i) (_hq : ∀ j, 0 < q j) (_hG : ∀ i j, 0 < G i j)
    (_hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (_hpotentials : IsFiniteSinkhornPotentialSystem p q G φ0 φhat0 φ1 φhat1) :
    Filter.Tendsto φ0Iter Filter.atTop (nhds φ0) ∧
    Filter.Tendsto φhat0Iter Filter.atTop (nhds φhat0) ∧
    Filter.Tendsto φ1Iter Filter.atTop (nhds φ1) ∧
    Filter.Tendsto φhat1Iter Filter.atTop (nhds φhat1) := by
  sorry

end ChenGeorgiouPavon2021
