#!/usr/bin/env bash
set -euo pipefail

# Setup lean4-skills for a Lean project.
#
# Usage:
#   bash dev/setup_lean4_skills.sh
#   bash dev/setup_lean4_skills.sh /path/to/lean/project
#
# Defaults are tuned for the current AIQ DRSB formalization repo.

PROJECT_ROOT="${1:-/home/joncrall/code/aiq-eval-runner/formalizations/aiq-drsb-formalization}"
INSTALL_ROOT="${LEAN4_SKILLS_INSTALL_ROOT:-$HOME/.local/share/lean4-skills}"
REPO_URL="${LEAN4_SKILLS_REPO_URL:-https://github.com/cameronfreer/lean4-skills.git}"
ENV_FILE="$PROJECT_ROOT/.lean4-skills.env"
AGENTS_FILE="$PROJECT_ROOT/AGENTS.md"

die() {
    echo "error: $*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

need_cmd git

mkdir -p "$(dirname "$INSTALL_ROOT")"

if [ -d "$INSTALL_ROOT/.git" ]; then
    echo "Updating lean4-skills at: $INSTALL_ROOT"
    git -C "$INSTALL_ROOT" fetch --depth 1 origin main
    git -C "$INSTALL_ROOT" checkout -q main
    git -C "$INSTALL_ROOT" reset --hard -q origin/main
else
    echo "Cloning lean4-skills into: $INSTALL_ROOT"
    git clone --depth 1 "$REPO_URL" "$INSTALL_ROOT"
fi

LEAN4_PLUGIN_ROOT="$INSTALL_ROOT/plugins/lean4"
LEAN4_SCRIPTS="$LEAN4_PLUGIN_ROOT/lib/scripts"
LEAN4_REFS="$LEAN4_PLUGIN_ROOT/skills/lean4/references"
LEAN4_SKILL_MD="$LEAN4_PLUGIN_ROOT/skills/lean4/SKILL.md"

[ -d "$PROJECT_ROOT" ] || die "project root does not exist: $PROJECT_ROOT"
[ -d "$LEAN4_PLUGIN_ROOT" ] || die "missing plugin root: $LEAN4_PLUGIN_ROOT"
[ -d "$LEAN4_SCRIPTS" ] || die "missing scripts directory: $LEAN4_SCRIPTS"
[ -d "$LEAN4_REFS" ] || die "missing references directory: $LEAN4_REFS"
[ -f "$LEAN4_SKILL_MD" ] || die "missing skill file: $LEAN4_SKILL_MD"

# The wrappers should already be executable, but make direct helper scripts usable too.
chmod +x "$LEAN4_PLUGIN_ROOT"/bin/lean4-skills-* 2>/dev/null || true
chmod +x "$LEAN4_SCRIPTS"/*.sh "$LEAN4_SCRIPTS"/*.py 2>/dev/null || true

cat > "$ENV_FILE" <<EOF
# Source this file from the Lean project root before using lean4-skills.
# Generated by dev/setup_lean4_skills.sh

export LEAN4_PLUGIN_ROOT="$LEAN4_PLUGIN_ROOT"
export LEAN4_SCRIPTS="\$LEAN4_PLUGIN_ROOT/lib/scripts"
export LEAN4_REFS="\$LEAN4_PLUGIN_ROOT/skills/lean4/references"
export PATH="\$LEAN4_PLUGIN_ROOT/bin:\$PATH"
EOF

echo "Wrote env file: $ENV_FILE"

# Optional generic skill discovery path for agents that support .agents/skills.
mkdir -p "$PROJECT_ROOT/.agents/skills"
ln -sfn "$LEAN4_PLUGIN_ROOT/skills/lean4" "$PROJECT_ROOT/.agents/skills/lean4"
echo "Linked project skill: $PROJECT_ROOT/.agents/skills/lean4 -> $LEAN4_PLUGIN_ROOT/skills/lean4"

# Add or replace a guarded AGENTS.md block.
mkdir -p "$PROJECT_ROOT"
touch "$AGENTS_FILE"

TMP_AGENTS="$(mktemp)"
awk '
    BEGIN { skip = 0 }
    /^<!-- lean4-skills:start -->$/ { skip = 1; next }
    /^<!-- lean4-skills:end -->$/ { skip = 0; next }
    skip == 0 { print }
' "$AGENTS_FILE" > "$TMP_AGENTS"

cat >> "$TMP_AGENTS" <<EOF

<!-- lean4-skills:start -->
## Lean 4 Workflows

This project is configured to use lean4-skills.

Skill reference:
- $LEAN4_SKILL_MD

Before running lean4-skills helper commands, source:

\`\`\`bash
source .lean4-skills.env
\`\`\`

Environment:
- LEAN4_PLUGIN_ROOT=$LEAN4_PLUGIN_ROOT
- LEAN4_SCRIPTS=\$LEAN4_PLUGIN_ROOT/lib/scripts
- LEAN4_REFS=\$LEAN4_PLUGIN_ROOT/skills/lean4/references
- PATH includes \$LEAN4_PLUGIN_ROOT/bin

Useful checks:

\`\`\`bash
command -v lean4-skills-sorry-analyzer
lean4-skills-sorry-analyzer . --format=summary --report-only
\`\`\`

Lean proof workflow notes:
- Prefer per-file checks with \`lake env lean path/to/File.lean\`.
- Use \`lake build\` as a final/project checkpoint gate.
- Do not change theorem statements or add axioms unless explicitly requested.
- Keep Lean lines near mathlib style, roughly 100 characters.
<!-- lean4-skills:end -->
EOF

mv "$TMP_AGENTS" "$AGENTS_FILE"
echo "Updated: $AGENTS_FILE"

# Verify wrapper path in a subshell so this script does not rely on caller env.
(
    cd "$PROJECT_ROOT"
    # shellcheck disable=SC1090
    source "$ENV_FILE"

    echo
    echo "Verification:"
    echo "  LEAN4_PLUGIN_ROOT=$LEAN4_PLUGIN_ROOT"
    echo "  LEAN4_SCRIPTS=$LEAN4_SCRIPTS"
    echo "  LEAN4_REFS=$LEAN4_REFS"

    command -v lean4-skills-sorry-analyzer

    if command -v lake >/dev/null 2>&1 && [ -f lakefile.lean -o -f lakefile.toml ]; then
        echo
        echo "Running sorry analyzer summary..."
        lean4-skills-sorry-analyzer . --format=summary --report-only
    else
        echo
        echo "Skipping project sorry analyzer: no lake project or lake unavailable."
    fi
)

cat <<EOF

Done.

For this shell:
  cd "$PROJECT_ROOT"
  source .lean4-skills.env

To persist globally, add this to ~/.bashrc or ~/.zshrc:
  source "$ENV_FILE"
EOF