/-
# Franklin--Lorenz finite matrix-scaling contraction seams

This file owns the paper-level Birkhoff--Hopf / Franklin--Lorenz Section 3 contraction input needed
by the finite Sinkhorn compactness proof.  It is intentionally separate from `ProjectiveLag.lean` so
future agents can work on the contraction port without touching the downstream compactness assembly.
-/

import ForMathlib.LinearAlgebra.Matrix.BirkhoffHopf
import ChenGeorgiouPavon2021.SocOt.Sinkhorn.Convergence.Compactness.MatrixBridge

set_option autoImplicit false

open MeasureTheory ProbabilityTheory
open scoped ENNReal BigOperators

namespace ChenGeorgiouPavon2021

/-- Two-sequence finite Franklin--Lorenz/Sinkhorn scaling orbit.

This is the mathlib-style abstraction behind the four-phase iterate system: `a` is the left
multiplicative scaling sequence and `b` is the right multiplicative scaling sequence.  The fields say
that the next left scaling normalizes rows to `p`, and the next right scaling normalizes columns to
`q`. -/
structure IsFiniteFranklinLorenzScalingOrbit {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (a b : ℕ → ι → ℝ) : Prop where
  left_pos : ∀ k i, 0 < a k i
  right_pos : ∀ k j, 0 < b k j
  row_update : ∀ k i, a (k + 1) i * (∑ j, G i j * b k j) = p i
  column_update : ∀ k j, b (k + 1) j * (∑ i, G i j * a k i) = q j

/-- Shared box-bounds hypothesis for the two scaling sequences in the Franklin--Lorenz
two-sequence orbit. -/
def FranklinLorenzScalingBoxBounds {ι : Type*}
    (a b : ℕ → ι → ℝ) : Prop :=
  ∃ ε B : ℝ, 0 < ε ∧ 0 < B ∧
    (∀ n i, ε ≤ a n i ∧ a n i ≤ B) ∧
    (∀ n j, ε ≤ b n j ∧ b n j ≤ B)

/-- The four-phase Sinkhorn box bounds imply the two-sequence Franklin--Lorenz box bounds for
`(φhat0Iter, φ1Iter)`. -/
theorem franklinLorenzScalingBoxBounds_of_sinkhornPhaseBoxBounds {ι : Type*}
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (hbounds : SinkhornPhaseBoxBounds φ0Iter φhat0Iter φ1Iter φhat1Iter) :
    FranklinLorenzScalingBoxBounds φhat0Iter φ1Iter := by
  rcases hbounds with ⟨ε, B, hε, hB, _hφ0, hφhat0, hφ1, _hφhat1⟩
  exact ⟨ε, B, hε, hB, hφhat0, hφ1⟩

/-- The four-phase Sinkhorn iterate package induces the two-sequence Franklin--Lorenz scaling orbit
for the left hatted scaling `φhat0Iter` and right scaling `φ1Iter`. -/
theorem sinkhorn_isFiniteFranklinLorenzScalingOrbit {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter) :
    IsFiniteFranklinLorenzScalingOrbit p q G φhat0Iter φ1Iter := by
  refine ⟨hiter.φhat0_pos, hiter.φ1_pos, ?_, ?_⟩
  · intro k i
    rw [← hiter.forward k i]
    exact hiter.normalize_left k i
  · intro k j
    rw [← hiter.backward k j]
    exact hiter.normalize_right k j

/-- Current column marginal for a two-sequence Franklin--Lorenz scaling orbit.

For left/right scalings `a k`, `b k`, this is the column-sum vector of the scaled matrix
`diag(a k) * G * diag(b k)`. -/
noncomputable def franklinLorenzCurrentColumnMarginal {ι : Type*} [Fintype ι]
    (G : ι → ι → ℝ) (a b : ℕ → ι → ℝ) (k : ℕ) : ι → ℝ :=
  fun j => (∑ i, G i j * a k i) * b k j

/-- Current column marginal generated by a right phase and a hatted-right denominator.

By `sinkhorn_rowNormalizedMatrix_column_sum`, this is the column-sum vector of the preceding
row-normalized matrix.  The right Sinkhorn update divides the target marginal `q` by this current
column marginal, so this vector is the natural Franklin--Lorenz column-error object. -/
abbrev sinkhornCurrentColumnMarginal {ι : Type*}
    (φ1Iter φhat1Iter : ℕ → ι → ℝ) (k : ℕ) : ι → ℝ :=
  fun j => φhat1Iter k j * φ1Iter k j

/-- The Sinkhorn current column marginal is the current column marginal of the two-sequence
Franklin--Lorenz scaling orbit `(φhat0Iter, φ1Iter)`. -/
theorem sinkhorn_currentColumnMarginal_eq_franklinLorenzCurrentColumnMarginal
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (k : ℕ) :
    sinkhornCurrentColumnMarginal φ1Iter φhat1Iter k =
      franklinLorenzCurrentColumnMarginal G φhat0Iter φ1Iter k := by
  funext j
  unfold sinkhornCurrentColumnMarginal franklinLorenzCurrentColumnMarginal
  rw [← hiter.backward k j]

/-- The current column marginal of a positive Franklin--Lorenz orbit is strictly positive. -/
theorem franklinLorenzCurrentColumnMarginal_pos {ι : Type*} [Fintype ι]
    (G : ι → ι → ℝ) (a b : ℕ → ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (ha_pos : ∀ k i, 0 < a k i)
    (hb_pos : ∀ k j, 0 < b k j)
    (k : ℕ) (j : ι) :
    0 < franklinLorenzCurrentColumnMarginal G a b k j := by
  classical
  unfold franklinLorenzCurrentColumnMarginal
  apply mul_pos
  · apply Finset.sum_pos
    · intro i _hi
      exact mul_pos (hG i j) (ha_pos k i)
    · exact ⟨j, Finset.mem_univ j⟩
  · exact hb_pos k j

/-- The target column marginal `q` is strictly positive along a positive Franklin--Lorenz orbit. -/
theorem franklinLorenz_targetColumn_pos {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (a b : ℕ → ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (horbit : IsFiniteFranklinLorenzScalingOrbit p q G a b)
    (k : ℕ) (j : ι) :
    0 < q j := by
  classical
  rw [← horbit.column_update k j]
  apply mul_pos
  · exact horbit.right_pos (k + 1) j
  · apply Finset.sum_pos
    · intro i _hi
      exact mul_pos (hG i j) (horbit.left_pos k i)
    · exact ⟨j, Finset.mem_univ j⟩

/-!
## Hard-core theorem ledger for the right `φ1` / column-correction path

The expanded Franklin--Lorenz notes make an important correction to the theorem shape: Hilbert's
projective metric controls **pairwise logarithmic oscillation** of the correction vector
`q / c_k`, not directly the pointwise quantity `|log (q_j / c_{k,j})|` relative to `1`.
Consequently the right-side proof should no longer pass through pointwise log-to-one error.

The remaining hard pieces for the right side are now:

1. `ForMathlib.Matrix.positive_kernel_birkhoff_contraction_coefficient` in `BirkhoffHopf.lean`:
   the paper-agnostic positive finite-kernel Birkhoff coefficient / strict contraction theorem.
2. `hard_core_franklinLorenz_right_column_pairwise_log_correction_geometric_bound`: the
   Franklin--Lorenz Lemma 2/Theorem 4 step giving geometric decay of the Hilbert/projective spread
   of the column correction vector `q / c_k`.
3. `hard_core_franklinLorenz_pairwise_correction_bound_of_pairwise_log_bound_and_ratio_box`: the
   finite real-analysis bridge from a pairwise log-ratio bound plus the already-proved finite box
   bound to the concrete pairwise difference bound needed by `finitePairwiseRatioSpread`.
4. `hard_core_sinkhorn_phihat0_forward_ratio_spread_geometric_bound`: the still-unmirrored left-side
   row-correction theorem.

The non-`hard_core_*` theorems below are wrappers used by downstream code; they should stay stable
while agents attack the hard-core theorem statements independently.
-/

/-- Hard core 2: Franklin--Lorenz / Birkhoff--Hopf projective log-oscillation decay for the right
column correction.

This is the theorem shape directly suggested by the expanded Franklin--Lorenz Section 3 notes:
Lemma 2 gives geometric decay of `d(c^(k), q)`, equivalently geometric decay of the Hilbert spread
of the correction vector `q / c^(k)`.  In coordinates, this controls the pairwise log-ratio

`|log ((q i / c_k i) / (q j / c_k j))|`.

This avoids the stronger and generally unjustified pointwise-to-one claim
`|log (q j / c_k j)| ≤ C γ^k`. -/
theorem hard_core_franklinLorenz_right_column_pairwise_log_correction_geometric_bound
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (a b : ℕ → ι → ℝ)
    (_hG : ∀ i j, 0 < G i j)
    (_horbit : IsFiniteFranklinLorenzScalingOrbit p q G a b)
    (_hbox : FranklinLorenzScalingBoxBounds a b)
    (γ : ℝ) (_hγ_nonneg : 0 ≤ γ) (_hγ_lt_one : γ < 1) :
    ∃ C : ℝ,
      0 ≤ C ∧
        ∀ k (ij : ι × ι),
          |Real.log
            ((q ij.1 / franklinLorenzCurrentColumnMarginal G a b k ij.1) /
              (q ij.2 / franklinLorenzCurrentColumnMarginal G a b k ij.2))| ≤ C * γ ^ k := by
  sorry

/-- Uniform finite-box bound for the right-column relative ratio `q / c_k`.

This is a finite-order/box-bounds seam, independent of Hilbert contraction.  From the update equation
`q_j = b_{k+1,j} * ∑_i G_ij a_{k,i}`, the quotient `q_j / c_{k,j}` is exactly
`b_{k+1,j} / b_{k,j}`, so the two-sequence box bounds give the uniform bound `B / ε`. -/
theorem franklinLorenz_right_column_relative_ratio_box_bound
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (a b : ℕ → ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (horbit : IsFiniteFranklinLorenzScalingOrbit p q G a b)
    (hbox : FranklinLorenzScalingBoxBounds a b) :
    ∃ R : ℝ,
      0 ≤ R ∧
        ∀ k j,
          |q j / franklinLorenzCurrentColumnMarginal G a b k j| ≤ R := by
  classical
  rcases hbox with ⟨ε, B, hε, hB, ha_box, hb_box⟩
  refine ⟨B / ε, le_of_lt (div_pos hB hε), ?_⟩
  intro k j
  let S : ℝ := ∑ i, G i j * a k i
  have hS_pos : 0 < S := by
    dsimp [S]
    apply Finset.sum_pos
    · intro i _hi
      exact mul_pos (hG i j) (horbit.left_pos k i)
    · exact ⟨j, Finset.mem_univ j⟩
  have hb_k_pos : 0 < b k j := lt_of_lt_of_le hε (hb_box k j).1
  have hb_next_nonneg : 0 ≤ b (k + 1) j :=
    le_trans (le_of_lt hε) (hb_box (k + 1) j).1
  have hratio_eq :
      q j / franklinLorenzCurrentColumnMarginal G a b k j = b (k + 1) j / b k j := by
    unfold franklinLorenzCurrentColumnMarginal
    dsimp [S] at hS_pos
    rw [← horbit.column_update k j]
    field_simp [ne_of_gt hS_pos, ne_of_gt hb_k_pos]
  have hmul : b (k + 1) j * ε ≤ B * b k j := by
    have h1 : b (k + 1) j * ε ≤ B * ε := by
      exact mul_le_mul_of_nonneg_right (hb_box (k + 1) j).2 (le_of_lt hε)
    have h2 : B * ε ≤ B * b k j := by
      exact mul_le_mul_of_nonneg_left (hb_box k j).1 (le_of_lt hB)
    exact le_trans h1 h2
  rw [hratio_eq]
  have hratio_nonneg : 0 ≤ b (k + 1) j / b k j :=
    div_nonneg hb_next_nonneg (le_of_lt hb_k_pos)
  rw [abs_of_nonneg hratio_nonneg]
  field_simp [ne_of_gt hb_k_pos, ne_of_gt hε]
  simpa [mul_comm, mul_left_comm, mul_assoc] using hmul

/-- Hard core 3: convert projective log-oscillation plus a ratio box into concrete pairwise
oscillation.

For positive ratios `r_i`, `r_j` bounded by `R`, a bound on `|log (r_i / r_j)|` should imply a
bound on `|r_i - r_j|` at the same geometric rate, with a larger constant depending on the box.
This is the faithful replacement for the earlier pointwise log-to-one conversion. -/
theorem hard_core_franklinLorenz_pairwise_correction_bound_of_pairwise_log_bound_and_ratio_box
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (a b : ℕ → ι → ℝ)
    (γ : ℝ) (_hγ_nonneg : 0 ≤ γ) (_hγ_lt_one : γ < 1)
    (_hratio_pos : ∀ k j, 0 < q j / franklinLorenzCurrentColumnMarginal G a b k j)
    (_hratio_box : ∃ R : ℝ,
      0 ≤ R ∧ ∀ k j, |q j / franklinLorenzCurrentColumnMarginal G a b k j| ≤ R)
    (_hlog : ∃ C : ℝ,
      0 ≤ C ∧
        ∀ k (ij : ι × ι),
          |Real.log
            ((q ij.1 / franklinLorenzCurrentColumnMarginal G a b k ij.1) /
              (q ij.2 / franklinLorenzCurrentColumnMarginal G a b k ij.2))| ≤ C * γ ^ k) :
    ∃ C : ℝ,
      0 ≤ C ∧
        ∀ k (ij : ι × ι),
          |q ij.1 / franklinLorenzCurrentColumnMarginal G a b k ij.1 -
            q ij.2 / franklinLorenzCurrentColumnMarginal G a b k ij.2| ≤ C * γ ^ k := by
  sorry

/-- Pairwise right-column correction oscillation bound for a two-sequence Franklin--Lorenz orbit.

This is now the composition of the faithful Franklin--Lorenz projective-log seam and the finite
real-analysis box conversion.  It no longer relies on the stronger pointwise-to-one log-error
statement. -/
theorem franklinLorenz_right_column_correction_pairwise_geometric_bound_of_birkhoff_coefficient
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (a b : ℕ → ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (horbit : IsFiniteFranklinLorenzScalingOrbit p q G a b)
    (hbox : FranklinLorenzScalingBoxBounds a b)
    (γ : ℝ) (hγ_nonneg : 0 ≤ γ) (hγ_lt_one : γ < 1) :
    ∃ C : ℝ,
      0 ≤ C ∧
        ∀ k (ij : ι × ι),
          |q ij.1 / franklinLorenzCurrentColumnMarginal G a b k ij.1 -
            q ij.2 / franklinLorenzCurrentColumnMarginal G a b k ij.2| ≤ C * γ ^ k := by
  have hratio_pos :
      ∀ k j, 0 < q j / franklinLorenzCurrentColumnMarginal G a b k j := by
    intro k j
    exact div_pos
      (franklinLorenz_targetColumn_pos p q G a b hG horbit k j)
      (franklinLorenzCurrentColumnMarginal_pos G a b hG horbit.left_pos horbit.right_pos k j)
  exact hard_core_franklinLorenz_pairwise_correction_bound_of_pairwise_log_bound_and_ratio_box
    p q G a b γ hγ_nonneg hγ_lt_one hratio_pos
    (franklinLorenz_right_column_relative_ratio_box_bound p q G a b hG horbit hbox)
    (hard_core_franklinLorenz_right_column_pairwise_log_correction_geometric_bound
      p q G a b hG horbit hbox γ hγ_nonneg hγ_lt_one)

/-- Pure two-sequence Franklin--Lorenz right-column correction geometric bound.

This theorem now performs only the finite-sum bookkeeping: the genuine contraction estimate is the
pairwise theorem
`franklinLorenz_right_column_correction_pairwise_geometric_bound_of_birkhoff_coefficient` above.
It has no four-phase Sinkhorn bookkeeping. -/
theorem franklinLorenz_right_column_correction_spread_geometric_bound_of_birkhoff_coefficient
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (a b : ℕ → ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (horbit : IsFiniteFranklinLorenzScalingOrbit p q G a b)
    (hbox : FranklinLorenzScalingBoxBounds a b)
    (γ : ℝ) (hγ_nonneg : 0 ≤ γ) (hγ_lt_one : γ < 1) :
    ∃ C : ℝ,
      0 ≤ C ∧
        ∀ k, ForMathlib.Matrix.finitePairwiseRatioSpread q
            (franklinLorenzCurrentColumnMarginal G a b k) ≤ C * γ ^ k := by
  obtain ⟨C, hC_nonneg, hpair⟩ :=
    franklinLorenz_right_column_correction_pairwise_geometric_bound_of_birkhoff_coefficient
      p q G a b hG horbit hbox γ hγ_nonneg hγ_lt_one
  refine ⟨(Fintype.card (ι × ι) : ℝ) * C,
    mul_nonneg (Nat.cast_nonneg _) hC_nonneg, ?_⟩
  intro k
  unfold ForMathlib.Matrix.finitePairwiseRatioSpread
  calc
    (∑ ij : ι × ι,
        |q ij.1 / franklinLorenzCurrentColumnMarginal G a b k ij.1 -
          q ij.2 / franklinLorenzCurrentColumnMarginal G a b k ij.2|)
        ≤ ∑ _ij : ι × ι, C * γ ^ k := by
          exact Finset.sum_le_sum (fun ij _hij => hpair k ij)
    _ = (Fintype.card (ι × ι) : ℝ) * (C * γ ^ k) := by
          simp
    _ = ((Fintype.card (ι × ι) : ℝ) * C) * γ ^ k := by
          ring

/-- Algebraic identification of the right forward correction spread with the spread of the column
marginal correction `q / currentColumnMarginal`.

This is a small but important orientation/phase-index lemma for the right-side port.  It should be
proved directly from `hiter.normalize_right k j`, positivity of `φ1Iter k j` and
`φhat1Iter k j`, and the definition of `finitePairwiseRatioSpread`. -/
theorem sinkhorn_phi1_forward_ratio_spread_eq_column_marginal_correction_spread
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (k : ℕ) :
    finiteForwardRatioSpread φ1Iter k =
      ForMathlib.Matrix.finitePairwiseRatioSpread q
        (sinkhornCurrentColumnMarginal φ1Iter φhat1Iter k) := by
  classical
  unfold finiteForwardRatioSpread ForMathlib.Matrix.finitePairwiseRatioSpread
    sinkhornCurrentColumnMarginal
  apply Finset.sum_congr rfl
  intro ij _hij
  have hi_ratio :
      φ1Iter (k + 1) ij.1 / φ1Iter k ij.1 =
        q ij.1 / (φhat1Iter k ij.1 * φ1Iter k ij.1) := by
    have hφ1_ne : φ1Iter k ij.1 ≠ 0 := ne_of_gt (hiter.φ1_pos k ij.1)
    have hφhat1_ne : φhat1Iter k ij.1 ≠ 0 := ne_of_gt (hiter.φhat1_pos k ij.1)
    have hprod_ne : φhat1Iter k ij.1 * φ1Iter k ij.1 ≠ 0 :=
      mul_ne_zero hφhat1_ne hφ1_ne
    have hnorm := hiter.normalize_right k ij.1
    field_simp [hφ1_ne, hprod_ne]
    nlinarith [hnorm]
  have hj_ratio :
      φ1Iter (k + 1) ij.2 / φ1Iter k ij.2 =
        q ij.2 / (φhat1Iter k ij.2 * φ1Iter k ij.2) := by
    have hφ1_ne : φ1Iter k ij.2 ≠ 0 := ne_of_gt (hiter.φ1_pos k ij.2)
    have hφhat1_ne : φhat1Iter k ij.2 ≠ 0 := ne_of_gt (hiter.φhat1_pos k ij.2)
    have hprod_ne : φhat1Iter k ij.2 * φ1Iter k ij.2 ≠ 0 :=
      mul_ne_zero hφhat1_ne hφ1_ne
    have hnorm := hiter.normalize_right k ij.2
    field_simp [hφ1_ne, hprod_ne]
    nlinarith [hnorm]
  rw [hi_ratio, hj_ratio]

/-- Right-side Franklin--Lorenz contraction target for the current column marginal correction.

This is now the real hard column-normalization port.  Starting from a strict Hilbert-projective
contraction coefficient `γ` for the positive kernel, Franklin--Lorenz Section 3 should give a finite
constant `C` such that the finite spread of the column correction `q / currentColumnMarginal` decays
geometrically.

Suggested proof route:
1. use `sinkhorn_rowNormalizedMatrix_column_sum` to identify
   `sinkhornCurrentColumnMarginal φ1Iter φhat1Iter k` with the column sums of the row-normalized
   matrix at step `k - 1` / the pre-column-normalization marginal error;
2. use the Birkhoff--Hopf contraction coefficient `γ` for the positive kernel to get the
   Franklin--Lorenz Lemma 2/Theorem 4 geometric estimate for those marginal-error corrections;
3. use `SinkhornPhaseBoxBounds` to translate Hilbert/projective correction control into the concrete
   finite quotient spread below. -/
theorem sinkhorn_phi1_column_marginal_correction_spread_geometric_bound_of_birkhoff_coefficient
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (_hgauge : IsFiniteSinkhornGaugeNormalized φ0Iter φhat0Iter φ1Iter φhat1Iter
      φ0 φhat0 φ1 φhat1)
    (hbounds : SinkhornPhaseBoxBounds φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (γ : ℝ) (hγ_nonneg : 0 ≤ γ) (hγ_lt_one : γ < 1) :
    ∃ C : ℝ,
      0 ≤ C ∧
        ∀ k, ForMathlib.Matrix.finitePairwiseRatioSpread q
            (sinkhornCurrentColumnMarginal φ1Iter φhat1Iter k) ≤ C * γ ^ k := by
  obtain ⟨C, hC_nonneg, hbound⟩ :=
    franklinLorenz_right_column_correction_spread_geometric_bound_of_birkhoff_coefficient
      p q G φhat0Iter φ1Iter hG
      (sinkhorn_isFiniteFranklinLorenzScalingOrbit p q G
        φ0Iter φhat0Iter φ1Iter φhat1Iter hiter)
      (franklinLorenzScalingBoxBounds_of_sinkhornPhaseBoxBounds
        φ0Iter φhat0Iter φ1Iter φhat1Iter hbounds)
      γ hγ_nonneg hγ_lt_one
  refine ⟨C, hC_nonneg, ?_⟩
  intro k
  rw [sinkhorn_currentColumnMarginal_eq_franklinLorenzCurrentColumnMarginal
    p q G φ0Iter φhat0Iter φ1Iter φhat1Iter hiter k]
  exact hbound k

/-- Right-side Franklin--Lorenz core under a chosen Birkhoff contraction coefficient.

The original right-side geometric-bound theorem is now just the composition of two smaller
right-side obligations: the phase algebra identifying the forward correction as `q / currentColumn`
and the Franklin--Lorenz geometric bound for that current-column correction spread. -/
theorem sinkhorn_phi1_forward_ratio_spread_geometric_bound_of_birkhoff_coefficient
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (hgauge : IsFiniteSinkhornGaugeNormalized φ0Iter φhat0Iter φ1Iter φhat1Iter
      φ0 φhat0 φ1 φhat1)
    (hbounds : SinkhornPhaseBoxBounds φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (γ : ℝ) (hγ_nonneg : 0 ≤ γ) (hγ_lt_one : γ < 1) :
    ∃ C : ℝ,
      0 ≤ C ∧ ∀ k, finiteForwardRatioSpread φ1Iter k ≤ C * γ ^ k := by
  obtain ⟨C, hC_nonneg, hbound⟩ :=
    sinkhorn_phi1_column_marginal_correction_spread_geometric_bound_of_birkhoff_coefficient
      p q G φ0Iter φhat0Iter φ1Iter φhat1Iter φ0 φhat0 φ1 φhat1
      hG hiter hgauge hbounds γ hγ_nonneg hγ_lt_one
  refine ⟨C, hC_nonneg, ?_⟩
  intro k
  rw [sinkhorn_phi1_forward_ratio_spread_eq_column_marginal_correction_spread
    p q G φ0Iter φhat0Iter φ1Iter φhat1Iter hiter k]
  exact hbound k

/-- Hard core 4: left-side Franklin--Lorenz row-correction geometric bound.

This is the row-normalization analogue of the right-side `φ1` development.  It should become much
less mysterious after the right-side log-error theorem is proved, because the remaining work should
mostly be the row/column orientation mirror. -/
theorem hard_core_sinkhorn_phihat0_forward_ratio_spread_geometric_bound
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ)
    (_hG : ∀ i j, 0 < G i j)
    (_hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (_hgauge : IsFiniteSinkhornGaugeNormalized φ0Iter φhat0Iter φ1Iter φhat1Iter
      φ0 φhat0 φ1 φhat1)
    (_hbounds : SinkhornPhaseBoxBounds φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (γ : ℝ) (_hγ_nonneg : 0 ≤ γ) (_hγ_lt_one : γ < 1) :
    ∃ C : ℝ,
      0 ≤ C ∧ ∀ k, finiteForwardRatioSpread φhat0Iter k ≤ C * γ ^ k := by
  sorry

/-- Stable wrapper around hard core 4. -/
theorem sinkhorn_phihat0_forward_ratio_spread_geometric_bound_of_birkhoff_coefficient
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (hgauge : IsFiniteSinkhornGaugeNormalized φ0Iter φhat0Iter φ1Iter φhat1Iter
      φ0 φhat0 φ1 φhat1)
    (hbounds : SinkhornPhaseBoxBounds φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (γ : ℝ) (hγ_nonneg : 0 ≤ γ) (hγ_lt_one : γ < 1) :
    ∃ C : ℝ,
      0 ≤ C ∧ ∀ k, finiteForwardRatioSpread φhat0Iter k ≤ C * γ ^ k := by
  exact hard_core_sinkhorn_phihat0_forward_ratio_spread_geometric_bound
    p q G φ0Iter φhat0Iter φ1Iter φhat1Iter φ0 φhat0 φ1 φhat1
    hG hiter hgauge hbounds γ hγ_nonneg hγ_lt_one

/-- Harder/right-side Franklin--Lorenz core: geometric decay of the column-correction spread.

The paper-agnostic strict contraction coefficient is supplied by the Mathlib-staging
Birkhoff--Hopf seam, and the Sinkhorn-specific work is isolated in
`sinkhorn_phi1_forward_ratio_spread_geometric_bound_of_birkhoff_coefficient`. -/
theorem sinkhorn_phi1_forward_ratio_spread_geometric_bound_from_franklin_lorenz
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (hgauge : IsFiniteSinkhornGaugeNormalized φ0Iter φhat0Iter φ1Iter φhat1Iter
      φ0 φhat0 φ1 φhat1)
    (hbounds : SinkhornPhaseBoxBounds φ0Iter φhat0Iter φ1Iter φhat1Iter) :
    ∃ C γ : ℝ,
      0 ≤ C ∧ 0 ≤ γ ∧ γ < 1 ∧
        ∀ k, finiteForwardRatioSpread φ1Iter k ≤ C * γ ^ k := by
  obtain ⟨γ, hγ_nonneg, hγ_lt_one⟩ :=
    ForMathlib.Matrix.positive_kernel_birkhoff_contraction_coefficient G hG
  obtain ⟨C, hC_nonneg, hbound⟩ :=
    sinkhorn_phi1_forward_ratio_spread_geometric_bound_of_birkhoff_coefficient
      p q G φ0Iter φhat0Iter φ1Iter φhat1Iter φ0 φhat0 φ1 φhat1
      hG hiter hgauge hbounds γ hγ_nonneg hγ_lt_one
  exact ⟨C, γ, hC_nonneg, hγ_nonneg, hγ_lt_one, hbound⟩

/-- Left-side Franklin--Lorenz core: geometric decay of the row-correction spread. -/
theorem sinkhorn_phihat0_forward_ratio_spread_geometric_bound_from_franklin_lorenz
    {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ)
    (hG : ∀ i j, 0 < G i j)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter)
    (hgauge : IsFiniteSinkhornGaugeNormalized φ0Iter φhat0Iter φ1Iter φhat1Iter
      φ0 φhat0 φ1 φhat1)
    (hbounds : SinkhornPhaseBoxBounds φ0Iter φhat0Iter φ1Iter φhat1Iter) :
    ∃ C γ : ℝ,
      0 ≤ C ∧ 0 ≤ γ ∧ γ < 1 ∧
        ∀ k, finiteForwardRatioSpread φhat0Iter k ≤ C * γ ^ k := by
  obtain ⟨γ, hγ_nonneg, hγ_lt_one⟩ :=
    ForMathlib.Matrix.positive_kernel_birkhoff_contraction_coefficient G hG
  obtain ⟨C, hC_nonneg, hbound⟩ :=
    sinkhorn_phihat0_forward_ratio_spread_geometric_bound_of_birkhoff_coefficient
      p q G φ0Iter φhat0Iter φ1Iter φhat1Iter φ0 φhat0 φ1 φhat1
      hG hiter hgauge hbounds γ hγ_nonneg hγ_lt_one
  exact ⟨C, γ, hC_nonneg, hγ_nonneg, hγ_lt_one, hbound⟩

end ChenGeorgiouPavon2021
