/-
# Finite Sinkhorn system scaffolding

This module contains the finite-dimensional data structures shared by the finite Sinkhorn
uniqueness and convergence targets.  The remaining proof obligations are intentionally kept out of
this file, so later agents can work either on the finite maximum-principle side or on the
finite-dimensional compactness side without editing the capstone target file.
-/

import ChenGeorgiouPavon2021.SocOt.Sinkhorn

set_option autoImplicit false

open MeasureTheory ProbabilityTheory
open scoped ENNReal BigOperators

namespace ChenGeorgiouPavon2021

/-- A finite Schrödinger/Sinkhorn potential system for prescribed marginals and positive kernel.

This packages the four positivity and four equation blocks so the uniqueness and convergence targets
speak about the same mathematical object.  Kernel positivity is intentionally kept as a theorem
hypothesis, not as a field here, because it is a condition on the reference kernel rather than on an
individual candidate solution. -/
structure IsFiniteSinkhornPotentialSystem {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ) : Prop where
  φ0_pos : ∀ i, 0 < φ0 i
  φhat0_pos : ∀ i, 0 < φhat0 i
  φ1_pos : ∀ j, 0 < φ1 j
  φhat1_pos : ∀ j, 0 < φhat1 j
  forward : ∀ i, φ0 i = ∑ j, G i j * φ1 j
  backward : ∀ j, φhat1 j = ∑ i, G i j * φhat0 i
  normalize_left : ∀ i, φ0 i * φhat0 i = p i
  normalize_right : ∀ j, φ1 j * φhat1 j = q j

/-- Pointwise ratio between two positive Sinkhorn potentials.  It is intentionally just the raw
quotient; nonzero denominators are supplied by the positivity fields at use sites. -/
noncomputable def sinkhornRatio {ι : Type*} (ψ φ : ι → ℝ) : ι → ℝ :=
  fun i => ψ i / φ i

/-- Abstract Fortet--IPF/Sinkhorn update equations for the finite target theorem.

This is intentionally an iterate specification, not a convergence assumption: it records that the
four displayed sequences are generated by the finite Sinkhorn update against marginals `p`, `q` and
positive kernel `G`.  Positivity is carried as part of the iterate package because the raw displayed
equations alone do not remember the positive seed needed for the finite Sinkhorn iteration. -/
structure IsFiniteSinkhornIterateSystem {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ) : Prop where
  φ0_pos : ∀ n i, 0 < φ0Iter n i
  φhat0_pos : ∀ n i, 0 < φhat0Iter n i
  φ1_pos : ∀ n j, 0 < φ1Iter n j
  φhat1_pos : ∀ n j, 0 < φhat1Iter n j
  forward : ∀ n i, φ0Iter n i = ∑ j, G i j * φ1Iter n j
  backward : ∀ n j, φhat1Iter n j = ∑ i, G i j * φhat0Iter n i
  normalize_left : ∀ n i, φhat0Iter (n + 1) i * φ0Iter n i = p i
  normalize_right : ∀ n j, φ1Iter (n + 1) j * φhat1Iter n j = q j

/-- Gauge choice for a particular representative of the scaling class.

Without some normalization, Sinkhorn potentials are determined only up to
`φ ↦ c • φ`, `φhat ↦ c⁻¹ • φhat`, so convergence to a named representative is over-specified.  This
predicate fixes the gauge by matching the total mass of the left forward potential at every iterate. -/
structure IsFiniteSinkhornGaugeNormalized {ι : Type*} [Fintype ι]
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (φ0 φhat0 φ1 φhat1 : ι → ℝ) : Prop where
  left_total : ∀ n, ∑ i, φ0Iter n i = ∑ i, φ0 i

/-- A phase-compatible cluster point along a concrete absolute subsequence.

The normalization equations mix phase `n` and phase `n+1`.  This predicate therefore records both
ordinary convergence along `subseq n` and the successor-phase convergence needed to pass the mixed
normalization equations to the limit.  Keeping the absolute subsequence explicit is important for the
full convergence proof, where every outer subsequence must have a further phase-compatible cluster
subsequence. -/
structure IsFiniteSinkhornClusterPointAlong {ι : Type*} [Fintype ι]
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (subseq : ℕ → ℕ) (ψ0 ψhat0 ψ1 ψhat1 : ι → ℝ) : Prop where
  strict_mono : StrictMono subseq
  tendsto_φ0 : Filter.Tendsto (fun n => φ0Iter (subseq n)) Filter.atTop (nhds ψ0)
  tendsto_φhat0 : Filter.Tendsto (fun n => φhat0Iter (subseq n)) Filter.atTop (nhds ψhat0)
  tendsto_φhat0_succ :
    Filter.Tendsto (fun n => φhat0Iter (subseq n + 1)) Filter.atTop (nhds ψhat0)
  tendsto_φ1 : Filter.Tendsto (fun n => φ1Iter (subseq n)) Filter.atTop (nhds ψ1)
  tendsto_φ1_succ :
    Filter.Tendsto (fun n => φ1Iter (subseq n + 1)) Filter.atTop (nhds ψ1)
  tendsto_φhat1 : Filter.Tendsto (fun n => φhat1Iter (subseq n)) Filter.atTop (nhds ψhat1)
  positive :
    (∀ i, 0 < ψ0 i) ∧
    (∀ i, 0 < ψhat0 i) ∧
    (∀ j, 0 < ψ1 j) ∧
    (∀ j, 0 < ψhat1 j)

/-- Phase-compatible subsequence cluster-point assertion for finite Sinkhorn iterates.

This existential wrapper preserves the old target-facing predicate while the harder convergence core
can now talk about cluster points along explicit subsequences via
`IsFiniteSinkhornClusterPointAlong`. -/
structure IsFiniteSinkhornClusterPoint {ι : Type*} [Fintype ι]
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (ψ0 ψhat0 ψ1 ψhat1 : ι → ℝ) : Prop where
  exists_subseq : ∃ subseq : ℕ → ℕ,
    IsFiniteSinkhornClusterPointAlong φ0Iter φhat0Iter φ1Iter φhat1Iter
      subseq ψ0 ψhat0 ψ1 ψhat1
  positive :
    (∀ i, 0 < ψ0 i) ∧
    (∀ i, 0 < ψhat0 i) ∧
    (∀ j, 0 < ψ1 j) ∧
    (∀ j, 0 < ψhat1 j)

/-- Positivity seam for the finite Sinkhorn iteration.

With positivity included in `IsFiniteSinkhornIterateSystem`, this is a projection lemma.  If the
iterate package is later refactored to carry only a positive seed, this is the theorem that should
be replaced by the actual induction proving positivity preservation. -/
theorem sinkhorn_iterates_positive {ι : Type*} [Fintype ι]
    (p q : ι → ℝ) (G : ι → ι → ℝ)
    (φ0Iter φhat0Iter φ1Iter φhat1Iter : ℕ → ι → ℝ)
    (hiter : IsFiniteSinkhornIterateSystem p q G φ0Iter φhat0Iter φ1Iter φhat1Iter) :
    (∀ n i, 0 < φ0Iter n i) ∧
    (∀ n i, 0 < φhat0Iter n i) ∧
    (∀ n j, 0 < φ1Iter n j) ∧
    (∀ n j, 0 < φhat1Iter n j) := by
  exact ⟨hiter.φ0_pos, hiter.φhat0_pos, hiter.φ1_pos, hiter.φhat1_pos⟩

end ChenGeorgiouPavon2021
