/-
# Sequence Gaussian Cameron--Martin: absolute continuity and dichotomy

This module closes the iid Gaussian sequence layer by proving square-summable
absolute continuity, the clean KL identity, and the finite/infinite dichotomy.
-/

import ForMathlib.MeasureTheory.GaussianCameronMartin.Density

set_option autoImplicit false

open MeasureTheory Real InformationTheory ProbabilityTheory Filter
open scoped BigOperators ENNReal NNReal

namespace ForMathlib.MeasureTheory

/-- The prefix filtration generated by the finite restrictions exhausts the ambient product
measurable space. -/
theorem iSup_prefixFiltration_eq :
    (⨆ n, prefixFiltration n) = (inferInstance : MeasurableSpace RealSeq) := by
  change (⨆ n, MeasurableSpace.comap (prefixRestrict n) inferInstance) =
    (inferInstance : MeasurableSpace RealSeq)
  simp_rw [← preorder_frestrictLe_eq_prefixRestrict]
  exact (iSup_comap_frestrictLe_eq_pi (ι := ℕ) (α := fun _ : ℕ => ℝ))

/-- The finite-prefix Cameron--Martin density process is adapted to the prefix filtration. -/
theorem stronglyAdapted_cmDensityProcess (c : RealSeq) :
    StronglyAdapted prefixFiltration (cmDensityProcess c) := by
  intro n
  change StronglyMeasurable[prefixFiltration n] (cmDensityProcess c n)
  change StronglyMeasurable[MeasurableSpace.comap (prefixRestrict n) inferInstance]
    (cmDensityProcess c n)
  have hprefix : @Measurable RealSeq (PrefixSpace n)
      (MeasurableSpace.comap (prefixRestrict n) inferInstance) inferInstance
      (prefixRestrict n) := by
    intro t ht
    exact ⟨t, ht, rfl⟩
  have hmeas : @Measurable RealSeq ℝ
      (MeasurableSpace.comap (prefixRestrict n) inferInstance) inferInstance
      (cmDensityProcess c n) := by
    have hcomp : @Measurable RealSeq ℝ
        (MeasurableSpace.comap (prefixRestrict n) inferInstance) inferInstance
        (fun x : RealSeq => finiteCmDensity (prefixRestrict n c) (prefixRestrict n x)) :=
      (measurable_finiteCmDensity (prefixRestrict n c)).comp hprefix
    convert hcomp using 1
    ext x
    exact finiteCmDensity_prefixRestrict c n x
  exact hmeas.stronglyMeasurable

/-- Square-summable deterministic shifts are absolutely continuous with respect to the iid
standard Gaussian sequence law.  This is `PLAN_CONTINUUM_CLOSURE.md` M2.8. -/
theorem absolutelyContinuous_stdSeqGaussian_map_add_of_summable (c : RealSeq)
    (hsum : Summable (fun n : ℕ => c n ^ 2)) :
    stdSeqGaussian.map (fun x : RealSeq => x + c) ≪ stdSeqGaussian := by
  haveI : IsProbabilityMeasure (stdSeqGaussian.map (fun x : RealSeq => x + c)) :=
    Measure.isProbabilityMeasure_map (measurable_shift c).aemeasurable
  refine absolutelyContinuous_of_localDensity
    (μ := stdSeqGaussian.map (fun x : RealSeq => x + c))
    (ν := stdSeqGaussian)
    (ℱ := prefixFiltration)
    (hgen := iSup_prefixFiltration_eq)
    (Z := cmDensityProcess c)
    (hadapted := stronglyAdapted_cmDensityProcess c)
    (hnonneg := cmDensityProcess_nonneg c)
    (hdens := map_add_eq_lintegral_cmDensityProcess c)
    (hM := ENNReal.ofReal_ne_top)
    (hL2 := lintegral_sq_cmDensityProcess_le c hsum)

/-- Clean square-summable sequence-model Cameron--Martin KL identity, with absolute
continuity discharged by the local-density/L² route. -/
theorem klDiv_stdSeqGaussian_map_add_of_summable (c : RealSeq)
    (hsum : Summable (fun n : ℕ => c n ^ 2)) :
    klDiv (stdSeqGaussian.map (fun x : RealSeq => x + c)) stdSeqGaussian
      = ENNReal.ofReal (cmTotalEnergy c) := by
  exact shift_kl_eq_cmTotalEnergy_of_summable c
    (absolutelyContinuous_stdSeqGaussian_map_add_of_summable c hsum) hsum

/-- Finiteness of the clean square-summable sequence-model KL identity. -/
theorem klDiv_stdSeqGaussian_map_add_ne_top_of_summable (c : RealSeq)
    (hsum : Summable (fun n : ℕ => c n ^ 2)) :
    klDiv (stdSeqGaussian.map (fun x : RealSeq => x + c)) stdSeqGaussian ≠ ⊤ := by
  rw [klDiv_stdSeqGaussian_map_add_of_summable c hsum]
  exact ENNReal.ofReal_ne_top

/-- Real-valued clean square-summable sequence-model Cameron--Martin KL identity. -/
theorem toReal_klDiv_stdSeqGaussian_map_add_of_summable (c : RealSeq)
    (hsum : Summable (fun n : ℕ => c n ^ 2)) :
    (klDiv (stdSeqGaussian.map (fun x : RealSeq => x + c)) stdSeqGaussian).toReal
      = cmTotalEnergy c := by
  rw [klDiv_stdSeqGaussian_map_add_of_summable c hsum]
  exact ENNReal.toReal_ofReal (cmTotalEnergy_nonneg c)


/-- Finiteness of the shifted-sequence KL is equivalent to square summability of the
shift.  The reverse implication uses the clean Cameron--Martin identity; the forward
implication extracts absolute continuity from finite KL and then applies the infinite-branch
contrapositive. -/
theorem summable_iff_klDiv_stdSeqGaussian_map_add_ne_top (c : RealSeq) :
    Summable (fun n : ℕ => c n ^ 2) ↔
      klDiv (stdSeqGaussian.map (fun x : RealSeq => x + c)) stdSeqGaussian ≠ ⊤ := by
  constructor
  · intro hsum
    exact klDiv_stdSeqGaussian_map_add_ne_top_of_summable c hsum
  · intro hfin
    haveI : IsProbabilityMeasure (stdSeqGaussian.map (fun x : RealSeq => x + c)) :=
      Measure.isProbabilityMeasure_map (measurable_shift c).aemeasurable
    exact summable_of_shift_kl_finite_of_ac c (klDiv_ne_top_iff.mp hfin).1 hfin

/-- The shifted-sequence KL is infinite exactly when the deterministic shift is not
square-summable. -/
theorem klDiv_stdSeqGaussian_map_add_eq_top_iff_not_summable (c : RealSeq) :
    klDiv (stdSeqGaussian.map (fun x : RealSeq => x + c)) stdSeqGaussian = ⊤ ↔
      ¬ Summable (fun n : ℕ => c n ^ 2) := by
  constructor
  · intro htop hsum
    exact (klDiv_stdSeqGaussian_map_add_ne_top_of_summable c hsum) htop
  · intro hnsum
    by_contra hfin
    exact hnsum ((summable_iff_klDiv_stdSeqGaussian_map_add_ne_top c).mpr hfin)

/-- Disjunctive version of the complete sequence-model Cameron--Martin dichotomy.
This avoids an `if Summable ... then ... else ...` statement, because summability is not a
computably decidable proposition in the theorem statement. -/
theorem klDiv_stdSeqGaussian_map_add_dichotomy (c : RealSeq) :
    (Summable (fun n : ℕ => c n ^ 2) ∧
        klDiv (stdSeqGaussian.map (fun x : RealSeq => x + c)) stdSeqGaussian =
          ENNReal.ofReal (cmTotalEnergy c)) ∨
      (¬ Summable (fun n : ℕ => c n ^ 2) ∧
        klDiv (stdSeqGaussian.map (fun x : RealSeq => x + c)) stdSeqGaussian = ⊤) := by
  classical
  by_cases hsum : Summable (fun n : ℕ => c n ^ 2)
  · exact Or.inl ⟨hsum, klDiv_stdSeqGaussian_map_add_of_summable c hsum⟩
  · exact Or.inr ⟨hsum, (klDiv_stdSeqGaussian_map_add_eq_top_iff_not_summable c).mpr hsum⟩

end ForMathlib.MeasureTheory
